name: Release

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
        - main

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14

      - name: Gradle Test
        run: ./gradlew allTests

      - name: Build Artifacts
        uses: gradle/gradle-build-action@v2

      - name: Release library
        run: ./gradlew publish -PGITHUB_USER=${{ secrets.CURRENT_GITHUB_USER }} -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
